name: ${project.name}
main: es.xdec0de.blp.BLP
author: xDec0de_
version: ${project.version}
softdepend: [BattleLevels, PlaceholderAPI]
commands:
  blp:
    usage: /<command> reload
    description: Reload the config.
